modLoader="javafml"
loaderVersion="[31,)"
authors="Example"

[[mods]]
modId="worldhandlerplugin"
version="1.15.2-1.0"
displayName="World Handler Plugin"
description='''
Example plugin for WorldHandler
'''

[[dependencies.worldhandlerplugin]]
    modId="worldhandler"
    mandatory=true
    versionRange="[1.15,)"
    ordering="NONE"
    side="BOTH"