modLoader="javafml"
loaderVersion="[33,)"
authors="Example"
license="License"

[[mods]]
modId="worldhandlerplugin"
version="1.16.5-1.0.2"
displayName="World Handler Plugin"
description='''
Example plugin for WorldHandler
'''

[[dependencies.worldhandlerplugin]]
    modId="worldhandler"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"