modLoader="javafml"
loaderVersion="[32,)"
authors="Example"

[[mods]]
modId="worldhandlerplugin"
version="1.16.1-1.0.1"
displayName="World Handler Plugin"
description='''
Example plugin for WorldHandler
'''

[[dependencies.worldhandlerplugin]]
    modId="worldhandler"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"