modLoader="javafml"
loaderVersion="[39,)"
authors="Example"
license="License"

[[mods]]
modId="worldhandlerplugin"
version="1.18.1-1.0.2"
displayName="World Handler Plugin"
description='''
Example plugin for WorldHandler
'''

[[dependencies.worldhandlerplugin]]
    modId="worldhandler"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"